function funpsy()

% FUNPSY toolbox for fMRI functional phase synchronization
%   Displays information about the toolbox version, authors and references

text=[
'\r\rFUNPSY toolbox for fMRI functional phase synchronization\r\r' ...
'RELEASE: 0.1 beta\r' ...
'CODE VERSION: 0.1.9\r' ...
'LATST MODIFIED: 2012/06/06\r' ...
'URL: http://code.google.com/p/funpsy/\r' ...
'RSS: http://code.google.com/p/funpsy/feeds\r' ...
'Please cite: doi:10.1089/brain.2011.0068\r' ...
'  Glerean, E., Salmi, J., Lahnakoski, J. M., J&auml;&auml;skel&auml;inen, I. P., & Sams, M. (2012). FMRI phase synchronization as a measure of dynamic functional connectivity. Brain connectivity. doi:10.1089/brain.2011.0068    \r' ...
'\r' ...
'Developed & maintained by: Enrico Glerean - enrico.glerean@aalto.fi\r' ...
'\r' ...
'Collaborators, co-authors, testers and other developers:   \r' ...
'  - Hanna Halme\r' ...
'  - Iiro Jääskeläinen\r' ...
'  - Juha Lahnakoski\r' ...
'  - Jouko Lampinen\r' ...
'  - Lauri Nummenmaa\r' ...
'  - Juha Salmi\r' ...
'  - Mikko Sams\r' ...
'  - Dmitry Smirnov\r\r' ...
'COPYRIGHT NOTICE\r' ...
'       IF YOU EDIT OR REUSE PART OF THE TOOLBOX CODE, PLEASE DO NOT RE-DISTRIBUTE WITHOUT NOTIFYING THE ORIGINAL AUTHOR\r' ...
'       IF YOU PUBLISH PLEASE QUOTE THE ORIGINAL ARTICLE ABOVE\r\r'
];

fprintf(text);
